"""add_exposure_module_tables

Revision ID: 79465b58a45b
Revises: 20260314_01
Create Date: 2026-03-22 08:40:46.392902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '79465b58a45b'
down_revision = '20260314_01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_exposure_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('avg_aqi', sa.Float(), nullable=False),
    sa.Column('max_aqi', sa.Integer(), nullable=False),
    sa.Column('min_aqi', sa.Integer(), nullable=False),
    sa.Column('pm25_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('exposure_score', sa.Float(), nullable=False),
    sa.Column('cigarette_equivalent', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_exposure_summary_date'), 'daily_exposure_summary', ['date'], unique=False)
    op.create_index(op.f('ix_daily_exposure_summary_user_id'), 'daily_exposure_summary', ['user_id'], unique=False)
    op.create_table('user_location_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('aqi_value', sa.Integer(), nullable=False),
    sa.Column('pm25', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_location_logs_timestamp'), 'user_location_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user_location_logs_user_id'), 'user_location_logs', ['user_id'], unique=False)
    op.create_table('users_health_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('asthma', sa.Boolean(), nullable=False),
    sa.Column('heart_disease', sa.Boolean(), nullable=False),
    sa.Column('commute_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_health_profile_user_id'), 'users_health_profile', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_health_profile_user_id'), table_name='users_health_profile')
    op.drop_table('users_health_profile')
    op.drop_index(op.f('ix_user_location_logs_user_id'), table_name='user_location_logs')
    op.drop_index(op.f('ix_user_location_logs_timestamp'), table_name='user_location_logs')
    op.drop_table('user_location_logs')
    op.drop_index(op.f('ix_daily_exposure_summary_user_id'), table_name='daily_exposure_summary')
    op.drop_index(op.f('ix_daily_exposure_summary_date'), table_name='daily_exposure_summary')
    op.drop_table('daily_exposure_summary')
    # ### end Alembic commands ###
